version: "3.9"

services:
  api:
    build: .
    container_name: clinic_manegement
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

    environment:
      DATABASE_URL: mysql+pymysql://root:883715@db:3306/clinic_db

  db:
    image: mysql:8
    container_name: clinic_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 883715
      MYSQL_DATABASE: clinic_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  
